services:
  langchat:
    build:
      context: ..
      dockerfile: docker/Dockerfile 
    image: langchat:latest 
    container_name: langchat
    volumes:
      - ../:/workspace               
      - /etc/localtime:/etc/localtime:ro
    working_dir: /workspace
    restart: always
    networks:
      - langchat_network
    ports:
      - "9009:9009" 
    environment:
      ENV_MODE: "production"
    command: python startup.py
  cerely_app:
    image: langchat:latest 
    container_name: celery_app
    volumes:
      - ../:/workspace               
      - /etc/localtime:/etc/localtime:ro
    working_dir: /workspace
    restart: always
    networks:
      - langchat_network
    command: celery -A celery_app worker --loglevel=info
    depends_on:
      - redis
  mineru_server:
    image: quincyqiang/mineru:0.1-models
    container_name: mineru_server
    restart: always
    networks:
      - langchat_network
    ports:
      - "8888:8000"
    volumes:
      - $HOME/.xinference:/root/.xinference
      - $HOME/.cache/huggingface:/root/.cache/huggingface
      - $HOME/.cache/modelscope:/root/.cache/modelscope
      - /etc/localtime:/etc/localtime:ro 
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  xinference:
    image: registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference:latest
    container_name: xinference
    restart: always
    networks:
      - langchat_network
    ports:
      - "9997:9997"
    volumes:
      - $HOME/.xinference:/root/.xinference
      - $HOME/.cache/huggingface:/root/.cache/huggingface
      - $HOME/.cache/modelscope:/root/.cache/modelscope
      - /etc/localtime:/etc/localtime:ro 
    environment:
      - HF_ENDPOINT=https://hf-mirror.com
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: xinference-local -H 0.0.0.0
  milvus:
    image: milvusdb/milvus:v2.4.1
    container_name: milvus
    command: milvus run standalone  1> /dev/null
    security_opt:
      - seccomp:unconfined
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd 
      - ETCD_CONFIG_PATH=/milvus/configs/embedEtcd.yaml
      - COMMON_STORAGETYPE=local
    volumes:
      - ./milvus/embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
      - ./volumes/milvus:/var/lib/milvus
      - /etc/localtime:/etc/localtime:ro
    networks:
      - langchat_network
    ports:
      - 19530:19530 
      - 9091:9091 
      - 2379:2379 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 90s
    restart: always
  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always
    networks:
      - langchat_network
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data
      - /etc/localtime:/etc/localtime:ro
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 90s
      
networks:
  langchat_network:
    driver: bridge
